name: C++ Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'arm64'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and run tests
      run: |
        docker buildx build --platform linux/arm64 -t scredis-test .
        docker run --platform linux/arm64 scredis-test make test