name: C++ Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: arm64v8/gcc:latest
      options: --platform linux/arm64

    steps:
    - uses: actions/checkout@v3

    - name: Build and run tests
      run: |
        make clean
        make test