name: C++ Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make

    - name: Build and run tests
      run: |
        make clean
        make test
      env:
        CXX: g++
        CXXFLAGS: "-std=c++17 -Wall -Wextra"
        OPTFLAGS: "-O3"
        ARCH: "-march=native"  # Using native architecture for CI environment